URL_SERVICE =  "https://cnt-fa3c9827-557c-4f31-a746-020e20304b6d.containerhub.tripleten-services.com"
# "copia la URL generada sin la barra inclinada al final"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/ "
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"